name: Cron Action
on:
  workflow_dispatch:
  schedule:
    - cron: '0 */1 * * *'


jobs:
  feedmeutimao:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install Requirements
        run: pip install -r requirements.txt
      - name: Run Main
        run: python main.py
        env:
          TOKEN_BOT: ${{ secrets.TOKEN_BOT }}
